g++ -o adb/client/usb_dispatch.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/client/usb_dispatch.cpp
g++ -o adb/client/usb_libusb.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/client/usb_libusb.cpp
g++ -o adb/client/usb_linux.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/client/usb_linux.cpp
g++ -o adb/adb.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb.cpp
g++ -o adb/adb_io.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb_io.cpp
g++ -o adb/socket_spec.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/socket_spec.cpp
g++ -o adb/adb_listeners.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb_listeners.cpp
g++ -o adb/adb_utils.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb_utils.cpp
g++ -o adb/sockets.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/sockets.cpp
g++ -o adb/transport.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/transport.cpp
g++ -o adb/transport_local.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/transport_local.cpp
g++ -o adb/transport_usb.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/transport_usb.cpp
g++ -o adb/services.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/services.cpp
g++ -o adb/adb_trace.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb_trace.cpp
g++ -o adb/diagnose_usb.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/diagnose_usb.cpp
g++ -o adb/adb_auth_host.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/adb_auth_host.cpp
g++ -o adb/sysdeps_unix.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=1 -fpermissive -I../boringssl/include -Iadb -Iinclude -Ibase/include -Ilibcrypto_utils/include -c adb/sysdeps_unix.cpp
g++ -o adb/fdevent.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=0 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -Iinclude -Ibase/include -c adb/fdevent.cpp
g++ -o adb/shell_service.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=0 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -Iinclude -Ibase/include -c adb/shell_service.cpp
g++ -o adb/shell_service_protocol.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -DADB_HOST=0 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -Iinclude -Ibase/include -c adb/shell_service_protocol.cpp
g++ -o adb/console.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/console.cpp
g++ -o adb/bugreport.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/bugreport.cpp
g++ -o adb/commandline.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/commandline.cpp
g++ -o adb/adb_client.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/adb_client.cpp
g++ -o adb/sysdeps/errno.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/sysdeps/errno.cpp
g++ -o adb/file_sync_client.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/file_sync_client.cpp
g++ -o adb/line_printer.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/line_printer.cpp
g++ -o adb/transport_mdns.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/transport_mdns.cpp
g++ -o adb/client/main.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_REVISION=\"$PKGVER\" -D_GNU_SOURCE -DADB_HOST=1 -D_Nonnull= -D_Nullable= -fpermissive -Iadb -I../mdnsresponder/mDNSShared -Iinclude -Ibase/include -c adb/client/main.cpp
g++ -o base/file.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/file.cpp
g++ -o base/logging.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/logging.cpp
g++ -o base/parsenetaddress.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/parsenetaddress.cpp
g++ -o base/stringprintf.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/stringprintf.cpp
g++ -o base/strings.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/strings.cpp
g++ -o base/errors_unix.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DADB_HOST=1 -D_GNU_SOURCE -Ibase/include -Iinclude -c base/errors_unix.cpp
gcc -o liblog/logger_write.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/logger_write.c
gcc -o liblog/local_logger.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/local_logger.c
gcc -o liblog/config_read.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/config_read.c
gcc -o liblog/logprint.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/logprint.c
gcc -o liblog/stderr_write.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/stderr_write.c
gcc -o liblog/config_write.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/config_write.c
gcc -o liblog/logger_lock.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/logger_lock.c
gcc -o liblog/logger_name.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/logger_name.c
gcc -o liblog/log_event_list.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/log_event_list.c
gcc -o liblog/log_event_write.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/log_event_write.c
gcc -o liblog/fake_log_device.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/fake_log_device.c
gcc -o liblog/fake_writer.c.o -std=gnu11 $CFLAGS $CPPFLAGS -DLIBLOG_LOG_TAG=1005 -DFAKE_LOG_DEVICE=1 -D_GNU_SOURCE -Ilog/include -Iinclude -c liblog/fake_writer.c
gcc -o libcutils/load_file.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/load_file.c
gcc -o libcutils/socket_inaddr_any_server_unix.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/socket_inaddr_any_server_unix.c
gcc -o libcutils/socket_local_client_unix.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/socket_local_client_unix.c
gcc -o libcutils/socket_local_server_unix.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/socket_local_server_unix.c
gcc -o libcutils/socket_loopback_server_unix.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/socket_loopback_server_unix.c
gcc -o libcutils/socket_network_client_unix.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/socket_network_client_unix.c
gcc -o libcutils/threads.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/threads.c
g++ -o libcutils/sockets.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/sockets.cpp
g++ -o libcutils/android_get_control_file.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/android_get_control_file.cpp
g++ -o libcutils/sockets_unix.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -D_GNU_SOURCE -Iinclude -c libcutils/sockets_unix.cpp
gcc -o libcrypto_utils/android_pubkey.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibcrypto_utils/include -I../boringssl/include -Iinclude -c libcrypto_utils/android_pubkey.c
gcc -o ../boringssl/src/crypto/bn/cmp.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/bn/cmp.c
gcc -o ../boringssl/src/crypto/bn/bn.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/bn/bn.c
gcc -o ../boringssl/src/crypto/bytestring/cbb.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/bytestring/cbb.c
gcc -o ../boringssl/src/crypto/mem.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/mem.c
gcc -o ../boringssl/src/crypto/buf/buf.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/buf/buf.c
gcc -o ../boringssl/src/crypto/bio/file.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/bio/file.c
gcc -o ../boringssl/src/crypto/bn/convert.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/bn/convert.c
gcc -o ../boringssl/src/crypto/base64/base64.c.o -std=gnu11 $CFLAGS $CPPFLAGS -I../boringssl/include -Iinclude -c ../boringssl/src/crypto/base64/base64.c
gcc -o ../mdnsresponder/mDNSShared/dnssd_ipc.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -DHAVE_IPV6 -DHAVE_LINUX -DNOT_HAVE_SA_LEN -DUSES_NETLINK -UMDNS_DEBUGMSGS -DMDNS_DEBUGMSGS=0 -I../mdnsresponder/mDNSShared -I../mdnsresponder/mDNSCore -Iinclude -c ../mdnsresponder/mDNSShared/dnssd_ipc.c
gcc -o ../mdnsresponder/mDNSShared/dnssd_clientstub.c.o -std=gnu11 $CFLAGS $CPPFLAGS -D_GNU_SOURCE -DHAVE_IPV6 -DHAVE_LINUX -DNOT_HAVE_SA_LEN -DUSES_NETLINK -UMDNS_DEBUGMSGS -DMDNS_DEBUGMSGS=0 -I../mdnsresponder/mDNSShared -I../mdnsresponder/mDNSCore -Iinclude -c ../mdnsresponder/mDNSShared/dnssd_clientstub.c
g++ -o adb/adb -lrt -ldl -lpthread -lcrypto -lutil -lusb-1.0 $LDFLAGS base/file.cpp.o base/logging.cpp.o base/parsenetaddress.cpp.o base/stringprintf.cpp.o base/strings.cpp.o base/errors_unix.cpp.o liblog/logger_write.c.o liblog/local_logger.c.o liblog/config_read.c.o liblog/logprint.c.o liblog/stderr_write.c.o liblog/config_write.c.o liblog/logger_lock.c.o liblog/logger_name.c.o liblog/log_event_list.c.o liblog/log_event_write.c.o liblog/fake_log_device.c.o liblog/fake_writer.c.o libcutils/load_file.c.o libcutils/socket_inaddr_any_server_unix.c.o libcutils/socket_local_client_unix.c.o libcutils/socket_local_server_unix.c.o libcutils/socket_loopback_server_unix.c.o libcutils/socket_network_client_unix.c.o libcutils/threads.c.o libcutils/sockets.cpp.o libcutils/android_get_control_file.cpp.o libcutils/sockets_unix.cpp.o ../boringssl/src/crypto/bn/cmp.c.o ../boringssl/src/crypto/bn/bn.c.o ../boringssl/src/crypto/bytestring/cbb.c.o ../boringssl/src/crypto/mem.c.o ../boringssl/src/crypto/buf/buf.c.o ../boringssl/src/crypto/bio/file.c.o ../boringssl/src/crypto/bn/convert.c.o ../boringssl/src/crypto/base64/base64.c.o libcrypto_utils/android_pubkey.c.o adb/client/usb_dispatch.cpp.o adb/client/usb_libusb.cpp.o adb/client/usb_linux.cpp.o adb/adb.cpp.o adb/adb_io.cpp.o adb/socket_spec.cpp.o adb/adb_listeners.cpp.o adb/adb_utils.cpp.o adb/sockets.cpp.o adb/transport.cpp.o adb/transport_local.cpp.o adb/transport_usb.cpp.o adb/services.cpp.o adb/adb_trace.cpp.o adb/diagnose_usb.cpp.o adb/adb_auth_host.cpp.o adb/sysdeps_unix.cpp.o adb/fdevent.cpp.o adb/shell_service.cpp.o adb/shell_service_protocol.cpp.o ../mdnsresponder/mDNSShared/dnssd_ipc.c.o ../mdnsresponder/mDNSShared/dnssd_clientstub.c.o adb/console.cpp.o adb/bugreport.cpp.o adb/commandline.cpp.o adb/adb_client.cpp.o adb/sysdeps/errno.cpp.o adb/file_sync_client.cpp.o adb/line_printer.cpp.o adb/transport_mdns.cpp.o adb/client/main.cpp.o
g++ -o fastboot/socket.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/socket.cpp
g++ -o fastboot/tcp.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/tcp.cpp
g++ -o fastboot/udp.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/udp.cpp
g++ -o fastboot/protocol.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/protocol.cpp
g++ -o fastboot/engine.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/engine.cpp
g++ -o fastboot/bootimg_utils.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/bootimg_utils.cpp
g++ -o fastboot/fastboot.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/fastboot.cpp
g++ -o fastboot/util.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/util.cpp
g++ -o fastboot/fs.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/fs.cpp
g++ -o fastboot/usb_linux.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -DFASTBOOT_REVISION=\"$PKGVER\" -D_GNU_SOURCE -Iadb -Iinclude -Imkbootimg -Ibase/include -Ilibsparse/include -I../extras/ext4_utils/include -I../extras/f2fs_utils -c fastboot/usb_linux.cpp
gcc -o libsparse/backed_block.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/backed_block.c
gcc -o libsparse/output_file.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/output_file.c
gcc -o libsparse/sparse.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/sparse.c
gcc -o libsparse/sparse_crc32.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/sparse_crc32.c
gcc -o libsparse/sparse_err.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/sparse_err.c
gcc -o libsparse/sparse_read.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -c libsparse/sparse_read.c
g++ -o libziparchive/zip_archive.cc.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -Ibase/include -Iinclude -c libziparchive/zip_archive.cc
g++ -o libutils/FileMap.cpp.o -std=gnu++14 $CXXFLAGS $CPPFLAGS -Iinclude -c libutils/FileMap.cpp
gcc -o ../extras/ext4_utils/make_ext4fs.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/make_ext4fs.c
gcc -o ../extras/ext4_utils/ext4fixup.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/ext4fixup.c
gcc -o ../extras/ext4_utils/ext4_utils.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/ext4_utils.c
gcc -o ../extras/ext4_utils/allocate.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/allocate.c
gcc -o ../extras/ext4_utils/contents.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/contents.c
gcc -o ../extras/ext4_utils/extent.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/extent.c
gcc -o ../extras/ext4_utils/indirect.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/indirect.c
gcc -o ../extras/ext4_utils/sha1.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/sha1.c
gcc -o ../extras/ext4_utils/wipe.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/wipe.c
gcc -o ../extras/ext4_utils/crc16.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/crc16.c
gcc -o ../extras/ext4_utils/ext4_sb.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Ilibsparse/include -Iinclude -I../extras/ext4_utils/include -c ../extras/ext4_utils/ext4_sb.c
g++ -o fastboot/fastboot -lpthread -lselinux -lz -lcrypto -lutil -lusb-1.0 $LDFLAGS libsparse/backed_block.c.o libsparse/output_file.c.o libsparse/sparse.c.o libsparse/sparse_crc32.c.o libsparse/sparse_err.c.o libsparse/sparse_read.c.o libziparchive/zip_archive.cc.o liblog/logger_write.c.o liblog/local_logger.c.o liblog/config_read.c.o liblog/logprint.c.o liblog/stderr_write.c.o liblog/config_write.c.o liblog/logger_lock.c.o liblog/logger_name.c.o liblog/log_event_list.c.o liblog/log_event_write.c.o liblog/fake_log_device.c.o liblog/fake_writer.c.o libutils/FileMap.cpp.o libcutils/load_file.c.o libcutils/socket_inaddr_any_server_unix.c.o libcutils/socket_local_client_unix.c.o libcutils/socket_local_server_unix.c.o libcutils/socket_loopback_server_unix.c.o libcutils/socket_network_client_unix.c.o libcutils/threads.c.o libcutils/sockets.cpp.o libcutils/android_get_control_file.cpp.o libcutils/sockets_unix.cpp.o ../boringssl/src/crypto/bn/cmp.c.o ../boringssl/src/crypto/bn/bn.c.o ../boringssl/src/crypto/bytestring/cbb.c.o ../boringssl/src/crypto/mem.c.o ../boringssl/src/crypto/buf/buf.c.o ../boringssl/src/crypto/bio/file.c.o ../boringssl/src/crypto/bn/convert.c.o ../boringssl/src/crypto/base64/base64.c.o libcrypto_utils/android_pubkey.c.o base/file.cpp.o base/logging.cpp.o base/parsenetaddress.cpp.o base/stringprintf.cpp.o base/strings.cpp.o base/errors_unix.cpp.o ../extras/ext4_utils/make_ext4fs.c.o ../extras/ext4_utils/ext4fixup.c.o ../extras/ext4_utils/ext4_utils.c.o ../extras/ext4_utils/allocate.c.o ../extras/ext4_utils/contents.c.o ../extras/ext4_utils/extent.c.o ../extras/ext4_utils/indirect.c.o ../extras/ext4_utils/sha1.c.o ../extras/ext4_utils/wipe.c.o ../extras/ext4_utils/crc16.c.o ../extras/ext4_utils/ext4_sb.c.o fastboot/socket.cpp.o fastboot/tcp.cpp.o fastboot/udp.cpp.o fastboot/protocol.cpp.o fastboot/engine.cpp.o fastboot/bootimg_utils.cpp.o fastboot/fastboot.cpp.o fastboot/util.cpp.o fastboot/fs.cpp.o fastboot/usb_linux.cpp.o adb/fdevent.cpp.o adb/shell_service.cpp.o adb/shell_service_protocol.cpp.o adb/client/usb_dispatch.cpp.o adb/client/usb_libusb.cpp.o adb/client/usb_linux.cpp.o adb/adb.cpp.o adb/adb_io.cpp.o adb/socket_spec.cpp.o adb/adb_listeners.cpp.o adb/adb_utils.cpp.o adb/sockets.cpp.o adb/transport.cpp.o adb/transport_local.cpp.o adb/transport_usb.cpp.o adb/services.cpp.o adb/adb_trace.cpp.o adb/diagnose_usb.cpp.o adb/adb_auth_host.cpp.o adb/sysdeps_unix.cpp.o
gcc -o libsparse/simg2img.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Iinclude -Ilibsparse/include -c libsparse/simg2img.c
g++ -o libsparse/simg2img -lz $LDFLAGS libsparse/backed_block.c.o libsparse/output_file.c.o libsparse/sparse.c.o libsparse/sparse_crc32.c.o libsparse/sparse_err.c.o libsparse/sparse_read.c.o libsparse/simg2img.c.o
gcc -o libsparse/img2simg.c.o -std=gnu11 $CFLAGS $CPPFLAGS -Iinclude -Ilibsparse/include -c libsparse/img2simg.c
g++ -o libsparse/img2simg -lz $LDFLAGS libsparse/backed_block.c.o libsparse/output_file.c.o libsparse/sparse.c.o libsparse/sparse_crc32.c.o libsparse/sparse_err.c.o libsparse/sparse_read.c.o libsparse/img2simg.c.o
